# Generated by Django 4.1.7 on 2023-03-18 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact1_contact2_contact3'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact3',
            new_name='dead',
        ),
        migrations.RenameModel(
            old_name='Contact1',
            new_name='harassement',
        ),
        migrations.RenameModel(
            old_name='Contact2',
            new_name='injured',
        ),
    ]
